### ISSUE TITLE
Form Code Generator broken?

### ISSUE THREAD

**Issue by max-luffe** [alvinwan/codegen#1]
Hi there,

Really nice app, I have tested a few times over the recent years.

The issue is that when transferring ownership, the Generator stops working. When you follow the install steps on the new owner account,  Google eventually comes with a "non verified app" disclaimer, even though the app still works on the original account (Same domain)

I've tried all the usual, emptying cache, uninstalling, reinstalling on the entire domain - nothing seems to work. What to do?

Thanks
m

![image](https://user-images.githubusercontent.com/60095271/72719688-e1620d00-3baa-11ea-877c-438a1ced9a2a.png)

![image](https://user-images.githubusercontent.com/60095271/72719744-fb035480-3baa-11ea-86db-2bd98d6fc768.png)

**Comment by alvinwan** [comment]
@max-luffe Thanks for posting here. It looks like add-ons require a new verification process for OAuth. I'm submitting a new verification request now and will update here when I receive approval.

**Comment by alvinwan** [comment]
Haha wow this was 2 years ago, but in any case, for anyone reading, this is resolved!
